// <auto-generated />
using BugNet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugNet.Migrations
{
    [DbContext(typeof(BugDbContext))]
    [Migration("20231120090957_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BugNet.Infrastructure.Models.Bug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bugs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Users unable to log in due to incorrect password validation.",
                            IsDone = false,
                            Name = "Login Page Authentication Issue"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Graphs on the dashboard are not displaying data accurately.",
                            IsDone = true,
                            Name = "Dashboard Graph Rendering Error"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The mobile app crashes immediately after launching on iOS devices.",
                            IsDone = false,
                            Name = "Mobile App Crash on Startup"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Some form submissions are not saving user-entered data into the database.",
                            IsDone = true,
                            Name = "Data Loss on Form Submission"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The search feature in the application is not providing expected search results.",
                            IsDone = false,
                            Name = "Search Functionality Not Returning Results"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Prices in the shopping cart are not being calculated accurately.",
                            IsDone = true,
                            Name = "Incorrect Price Calculation in Shopping Cart"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Users encounter an error when attempting to upload documents larger than 5MB.",
                            IsDone = false,
                            Name = "File Upload Error in Documents Section"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Some navigation menu items are not visible to certain user roles.",
                            IsDone = true,
                            Name = "Missing Navigation Menu Items"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Email notifications are not being sent out to users as expected.",
                            IsDone = false,
                            Name = "Notification System Fails to Deliver Emails"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Font sizes vary inconsistently across different pages of the application.",
                            IsDone = true,
                            Name = "Inconsistent Font Sizes Across Web Pages"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
